text = """
oba@arukurashi.com
month2024.i.tile@gmail.com
baybrookpanna@gmail.com
info@nighthawksfk.com
info@morpheeleather.com
tigre@tenkumaru.com
tigre@tenkumaru.com
neoclub@5570.jp
tanaka@larco.jp
last6child@gmail.com
info@navyharrys.com
chanco0875@gmail.com
info@morpheeleather.com
harrysthearmygym@gmail.com
scene.ninetynine@gmail.com
info@daisuekfurukawa.com
pm.mgr.inuzuka@gmail.com
miyazaki.725@docomo.ne.jp
yamamoto@atdc.com
fukuoka@blancoweb.com
info.choo@gmail.com
giraffe 63@vivid.ocn.ne.jp 
kakiuchi_mika@iwatayamitsukoshi.co.jp
beans@noahdesign.jp
uchida_kokoro@iwatayamitsukoshi.co.jp
leathertramp2011@yahoo.co.jp
herencia.cad@gmail.com
4rimichi.akizuki@gmail.com
penneys_vintage@ybb.ne.jp
matsuoka_anna@iwatayamitsukoshi.co.jp
lotus@titan.ocn.ne.jp
herencia.kikunaga@minos.ocn.ne.jp
mi521 @watanabeya.co.jp
beans@net.email.ne.jp
info@karatsushirtkoubou.com
matsuya@hug2.jp
contact@circlestyle.com
info@robinaso.com
yuzumitu123@gmail.com
ren.shintani@gmail.com
info@redgoodspeed.com
masahiro.nishikawa0129@gmail.com
desaki19@yahoo.co.jp
info@dayzsales.com
rk 515@watanabeya.co.jp
doubleheart@lake.ocn.ne.jp
nagashimamasahiko@lautrec.co.jp
beans@noahdesign.jp
attic_shop@million.vc
retrick0401@gmail.com
yamamoto@srlinc.com
yshow@purple.plala.or.jp
chiharu.ueda@onthebooks.jp
fobstore@ifn.ne.jp
labasse@topaz.plala.or.jp
muffyame@gmail.com
takayama@sanzentokyo.com
soejima@provokedb.com
nakashima@provokedb.com
info@magicuco.com
pmkominkan@gmail.com
haruna@sanzentokyo.com
mahiro_horie@libwork.co.jp
takayuki_kitamoto@libwork.co.jp
yyuasa@tw.caitac.co.jp
wyoshimoto@tw.caitac.co.jp
okada@sekimiki.co.jp
onizaki@sekimiki.co.jp
ogawa@sekimiki.co.jp
stereo.mk3@gmail.com
stereo.mk3@gmail.com
info@ampersandand.co.jp
otaguro@felicita96.co.jp
howzit.hoshiyama@gmail.com
t.tokorozaki@stylew.co.jp
info@bisa.co.jp
info@mmcloset.com
mai@chabbit.com
mai@chabbit.com
meimai@izutsuya.co.jp
nononaka@izutsuya.co.jp
tigermilk@nifty.com
info@toilekokura.jp
hoe@unicshoji.co.jp
ayano@okamotoshoten.co.jp
maisonblanche@annem.co.jp
rire@rire.ocnk.net
meets1974@gmail.com
vw1972vw@icloud.com
marroud25@ozzio.jp
tinkle.air@gmail.com
iguchi@mamekurogouchi.com
kanomata@mamekurogouchi.com
mitomij@ideaport.co.jp
tayan@omula.ac.jp
tanakaseiko@omula.ac.jp
cocoro1020@gmail.com
yamamoto_ginga@iwatayamitsukoshi.co.jp
nagai_keika@iwatayamitsukoshi.co.jp
kawakami_kazue@iwatayamitsukoshi.co.jp
jump@mavazi.jp
tomohito.shigeta@hakuhodo.co.jp
ytsuji@nishikawanet.com
akao@becrews.co.jp
branch@baybrook.co.jp
jump@mavazi.jp
tenkumaru@tenkumaru.com
stylecouncil@maruya.co.jp
dico2321@gmail.com
minoya.buyer@vesta.ocn.ne.jp
seisan@tenkumaru.com
tenkumaru@tenkumaru.com
yahata@linkitall.jp
info@mamekurogouchi.com
kasikaya12@gmail.com
kikaku@tenkumaru.com
kikaku@tenkumaru.com
press@bluebeat.co.jp
hiromik@coconutworld.com
tenkumaru@tenkumaru.com
tide@johnbull.co.jp
tenkumaru@tenkumaru.com
gatsgrand721@yahoo.co.jp
tenkumaru@tenkumaru.com
ral@coconutworld.com
bingo.bhc131@gmail.com
oba@arukurashi.com
paulinebleu0215@gmail.com
nakayama@hightide.co.jp
info@magicu.jp
info@hangarm.com
yano@fashionballoon.co.jp
tibetan@luck.ocn.ne.jp
famille@wing.ocn.ne.jp
suehiro@goshjp.com
francis7014@icloud.com
aulico@blue.plala.or.jp
kiharu@quantizedressline.com
saudadefn@icloud.com
mail@localmaison.com
"""

# 行ごとに分割して空行を除去
emails = [line.strip() for line in text.splitlines() if line.strip()]

# ダブルクォートで囲んでカンマで連結
result = ",".join(f'"{email}"' for email in emails)

print(result)
